version: '3.8'

services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - OWNER_ID=${OWNER_ID}
      - BACKUP_CHANNEL_ID=${BACKUP_CHANNEL_ID}
      - RENDER=true
    restart: unless-stopped